In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('fb.csv')

In [3]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [4]:
df.shape

(500, 19)

In [5]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [7]:
df.iloc[-1::-1 ,1:9:3]

       Type  Post Weekday  Lifetime Post Total Reach
499   Photo             4                       4188
498   Photo             4                       4156
497   Photo             5                       3778
496   Photo             5                       3480
495   Photo             7                       4684
..      ...           ...                        ...
4     Photo             2                       7244
3     Photo             2                      50128
2     Photo             3                       2413
1    Status             3                      10460
0     Photo             4                       2752

[500 rows x 3 columns]

In [8]:
df.loc[3]

Page total likes                                                       139441
Type                                                                    Photo
Category                                                                    2
Post Month                                                                 12
Post Weekday                                                                2
Post Hour                                                                  10
Paid                                                                      1.0
Lifetime Post Total Reach                                               50128
Lifetime Post Total Impressions                                         87991
Lifetime Engaged Users                                                   2211
Lifetime Post Consumers                                                   790
Lifetime Post Consumptions                                               1119
Lifetime Post Impressions by people who have liked your Page            61027
Lifetime Post reach by people who like your Page                        32048
Lifetime People who have liked your Page and engaged with your post      1386
comment                                                                    58
like                                                                   1572.0
share                                                                   147.0
Total Interactions                                                       1777
Name: 3, dtype: object

In [9]:
subset = df.loc[ : , ['Page total likes','Type','Post Month', 'like','share','comment']]
print("\n Subset values :\n",subset.head())

 Subset values :
    Page total likes    Type  Post Month    like  share  comment
0            139441   Photo          12    79.0   17.0        4
1            139441  Status          12   130.0   29.0        5
2            139441   Photo          12    66.0   14.0        0
3            139441   Photo          12  1572.0  147.0       58
4            139441   Photo          12   325.0   49.0       19

In [10]:
merged_df = pd.DataFrame({'Type' : ['Photo','Status'],'Category' :['Visual','Textual']})
merge = pd.merge(subset,merged_df,on='Type',how = 'left')
print("\n merged values :\n",merge.head())

 merged values :
    Page total likes    Type  Post Month    like  share  comment Category
0            139441   Photo          12    79.0   17.0        4   Visual
1            139441  Status          12   130.0   29.0        5  Textual
2            139441   Photo          12    66.0   14.0        0   Visual
3            139441   Photo          12  1572.0  147.0       58   Visual
4            139441   Photo          12   325.0   49.0       19   Visual

In [11]:
sorted_df = merge.sort_values(by = 'like',ascending = False)
print("\n Sorted values :\n",sorted_df.head())

 Sorted values :
      Page total likes   Type  Post Month    like  share  comment Category
244            130791  Photo           7  5172.0  790.0      372   Visual
379            111620  Photo           4  1998.0  128.0       51   Visual
349            117764  Photo           5  1639.0  122.0       45   Visual
168            135428  Photo           9  1622.0  208.0      144   Visual
3              139441  Photo          12  1572.0  147.0       58   Visual

In [12]:
print("\n Subset values :\n",sorted_df.head(6).T)

 Subset values :
                      244     379     349     168     3       460
Page total likes  130791  111620  117764  135428  139441   92507
Type               Photo   Photo   Photo   Photo   Photo   Photo
Post Month             7       4       5       9      12       2
like              5172.0  1998.0  1639.0  1622.0  1572.0  1546.0
share              790.0   128.0   122.0   208.0   147.0   181.0
comment              372      51      45     144      58     146
Category          Visual  Visual  Visual  Visual  Visual  Visual

In [13]:
melted = pd.melt(subset.head(),id_vars = ['Type'])
print("\n Melted values :\n",melted.head())

 Melted values :
      Type          variable     value
0   Photo  Page total likes  139441.0
1  Status  Page total likes  139441.0
2   Photo  Page total likes  139441.0
3   Photo  Page total likes  139441.0
4   Photo  Page total likes  139441.0

In [19]:
## ii. Pivot (Casting): Long → Wide
casted = melted.pivot_table(index='Type', columns='variable', values='value', aggfunc='first')
print(casted)

variable  Page total likes  Post Month  comment   like  share
Type
Photo             139441.0        12.0      4.0   79.0   17.0
Status            139441.0        12.0      5.0  130.0   29.0